# Generated by Django 4.2.5 on 2023-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
