# Generated by Django 4.2.5 on 2023-10-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0002_service_cost_amount_delete_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vetapp.clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
