# Generated by Django 4.2.5 on 2023-10-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0006_service_cost_amount_delete_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost_amount',
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetapp.service')),
            ],
            options={
                'verbose_name_plural': 'Costs',
            },
        ),
    ]
