# Generated by Django 4.2.5 on 2023-10-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0007_remove_service_cost_amount_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AlterField(
            model_name='cost',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vetapp.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(to='vetapp.service'),
        ),
    ]
