# Generated by Django 4.2.5 on 2023-10-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0008_remove_appointment_service_alter_cost_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name_plural': 'Clinics'},
        ),
    ]
