# Generated by Django 4.2.5 on 2023-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0010_alter_clinicreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicreview',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
