# Generated by Django 4.2.5 on 2023-10-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0011_alter_clinicreview_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
