# Generated by Django 4.2.5 on 2023-10-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0012_clinicdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingletonClinicDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('site_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vetapp.clinicdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
