# Generated by Django 4.2.5 on 2023-10-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0013_singletonclinicdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingletonClinicDescription',
        ),
    ]
