# Generated by Django 4.2.5 on 2023-10-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0015_alter_clinicdescription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
