# Generated by Django 4.2.5 on 2023-10-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0018_remove_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=79519701717, max_length=12),
            preserve_default=False,
        ),
    ]
