# Generated by Django 4.2.5 on 2023-10-06 03:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0021_appointment_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU'),
        ),
    ]
