# Generated by Django 4.2.5 on 2023-10-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0022_alter_appointment_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
